
630 filas insertadas.


27,190 filas insertadas.


Error que empieza en la línea: 7 del comando :
INSERT  INTO dfam
SELECT * FROM "dfam"@ifmx
Informe de error -
ORA-02290: restricción de control (ADMIN.CK_FAM_CED_ORD) violada


1 fila insertadas.


2,958 filas insertadas.

Confirmación terminada.

0 filas insertadas.


23,787 filas insertadas.


174 filas insertadas.


470 filas insertadas.


16,090 filas insertadas.


22,009 filas insertadas.


26,734 filas insertadas.


0 filas insertadas.

Confirmación terminada.

4,012 filas insertadas.


0 filas insertadas.


0 filas insertadas.


32 filas insertadas.


40,116 filas insertadas.


0 filas insertadas.


27,105 filas insertadas.


512 filas insertadas.


100 filas insertadas.


11,026 filas insertadas.


0 filas insertadas.


314,657 filas insertadas.

Confirmación terminada.

199 filas insertadas.


4 filas insertadas.


4 filas insertadas.


0 filas insertadas.


1,224 filas insertadas.


0 filas insertadas.


76,702 filas insertadas.


2 filas insertadas.


39,945 filas insertadas.


11,036,172 filas insertadas.


2,413 filas insertadas.


194 filas insertadas.


400 filas insertadas.


0 filas insertadas.


681 filas insertadas.


21,855 filas insertadas.


28 filas insertadas.


6 filas insertadas.


5 filas insertadas.


23,390 filas insertadas.


19,477 filas insertadas.


67,621 filas insertadas.


12,610 filas insertadas.


1 fila insertadas.


129,839 filas insertadas.

Confirmación terminada.

22 filas insertadas.


0 filas insertadas.


0 filas insertadas.


0 filas insertadas.


0 filas insertadas.


2 filas insertadas.


13 filas insertadas.


0 filas insertadas.


15 filas insertadas.


4 filas insertadas.


2,561 filas insertadas.


0 filas insertadas.


39 filas insertadas.


10 filas insertadas.


12 filas insertadas.


10,845 filas insertadas.


71 filas insertadas.


24 filas insertadas.


5 filas insertadas.


5 filas insertadas.

Confirmación terminada.

3 filas insertadas.


0 filas insertadas.


0 filas insertadas.


11 filas insertadas.


58 filas insertadas.


283,865 filas insertadas.


13,381 filas insertadas.


0 filas insertadas.


229 filas insertadas.


585 filas insertadas.


0 filas insertadas.


36 filas insertadas.


0 filas insertadas.


114 filas insertadas.


0 filas insertadas.


0 filas insertadas.


0 filas insertadas.


0 filas insertadas.


0 filas insertadas.


0 filas insertadas.


0 filas insertadas.


666 filas insertadas.


3,689 filas insertadas.


0 filas insertadas.


0 filas insertadas.


1,659 filas insertadas.


0 filas insertadas.


0 filas insertadas.


0 filas insertadas.

Confirmación terminada.

0 filas insertadas.


1 fila insertadas.


0 filas insertadas.


20,875 filas insertadas.


20,677 filas insertadas.


1 fila insertadas.


0 filas insertadas.


0 filas insertadas.


67,531 filas insertadas.


0 filas insertadas.


973 filas insertadas.


0 filas insertadas.


11,058,105 filas insertadas.


993 filas insertadas.


1 fila insertadas.


0 filas insertadas.


35,747 filas insertadas.


1,068 filas insertadas.


0 filas insertadas.


0 filas insertadas.


3,720 filas insertadas.


10,348 filas insertadas.


0 filas insertadas.


1 fila insertadas.


0 filas insertadas.


0 filas insertadas.


0 filas insertadas.


37,197 filas insertadas.

Confirmación terminada.

Error que empieza en la línea: 396 del comando :
INSERT  INTO cc_dticket
SELECT * FROM "cc_dticket"@ifmx
Informe de error -
ORA-01843: mes no válido


Error que empieza en la línea: 399 del comando :
INSERT  INTO cc_mticket
SELECT * FROM "cc_mticket"@ifmx
Informe de error -
ORA-01843: mes no válido


0 filas insertadas.


0 filas insertadas.


Error que empieza en la línea: 408 del comando -
INSERT  INTO aud_insp_inmuebles
SELECT * FROM "--"@ifmx
Error en la línea de comandos : 409 Columna : 15
Informe de error -
Error SQL: ORA-00942: la tabla o vista no existe
[Informix][Informix ODBC Driver][Informix]The specified table (--) is not in the database. {42S02,NativeErr = -206}
ORA-02063: 2 lines precediendo a IFMX
00942. 00000 -  "table or view does not exist"
*Cause:    
*Action:

301 filas insertadas.


32 filas insertadas.


108 filas insertadas.


2 filas insertadas.


4 filas insertadas.


1 fila insertadas.


172 filas insertadas.


0 filas insertadas.


0 filas insertadas.


77 filas insertadas.


571 filas insertadas.


5,470 filas insertadas.


144 filas insertadas.


52 filas insertadas.


41 filas insertadas.


329 filas insertadas.


380 filas insertadas.


0 filas insertadas.


33 filas insertadas.


0 filas insertadas.


803 filas insertadas.


1,319 filas insertadas.


10 filas insertadas.


10 filas insertadas.


2,936 filas insertadas.

Confirmación terminada.

0 filas insertadas.


697 filas insertadas.


2,191 filas insertadas.


3,597 filas insertadas.


1,682 filas insertadas.


0 filas insertadas.


7 filas insertadas.


75 filas insertadas.


0 filas insertadas.


18,069 filas insertadas.


147,065 filas insertadas.


0 filas insertadas.


16 filas insertadas.


0 filas insertadas.


0 filas insertadas.


8 filas insertadas.


3 filas insertadas.


1,708 filas insertadas.


3 filas insertadas.


40,567 filas insertadas.


228 filas insertadas.


19 filas insertadas.


5 filas insertadas.


499 filas insertadas.


629 filas insertadas.


30 filas insertadas.


2,291 filas insertadas.

Confirmación terminada.

0 filas insertadas.


53,552 filas insertadas.


1,065 filas insertadas.


1,475 filas insertadas.


2,093 filas insertadas.


0 filas insertadas.


0 filas insertadas.


37,164 filas insertadas.


13 filas insertadas.


371 filas insertadas.


13 filas insertadas.


7 filas insertadas.


79 filas insertadas.


Error que empieza en la línea: 610 del comando :
INSERT  INTO co_mper
SELECT * FROM "co_mper"@ifmx
Informe de error -
ORA-02290: restricción de control (ADMIN.CK_PER_CED_ORD) violada


0 filas insertadas.


2 filas insertadas.


6 filas insertadas.


0 filas insertadas.


1,341 filas insertadas.


11,068 filas insertadas.


19,403 filas insertadas.


0 filas insertadas.


1 fila insertadas.


19,156 filas insertadas.


25,931 filas insertadas.


25 filas insertadas.


549 filas insertadas.


1,052,935 filas insertadas.


5,840,376 filas insertadas.


10,113,916 filas insertadas.


644,608 filas insertadas.


650,406 filas insertadas.


5 filas insertadas.


3 filas insertadas.


4 filas insertadas.


3 filas insertadas.


30 filas insertadas.


0 filas insertadas.


23 filas insertadas.


12 filas insertadas.


42 filas insertadas.


1,671 filas insertadas.


428 filas insertadas.


548 filas insertadas.


0 filas insertadas.


105 filas insertadas.


0 filas insertadas.


103,789 filas insertadas.


283 filas insertadas.


0 filas insertadas.


0 filas insertadas.


8 filas insertadas.


77 filas insertadas.


4 filas insertadas.


3 filas insertadas.


4 filas insertadas.


94 filas insertadas.


8 filas insertadas.


4 filas insertadas.


7 filas insertadas.


17 filas insertadas.


4 filas insertadas.


4 filas insertadas.


0 filas insertadas.


0 filas insertadas.


0 filas insertadas.


2 filas insertadas.


371 filas insertadas.


493,814 filas insertadas.


1,174,625 filas insertadas.


1,074,166 filas insertadas.


14,699 filas insertadas.


46,711 filas insertadas.


1,099 filas insertadas.

Confirmación terminada.

29,711 filas insertadas.


493 filas insertadas.


2,790 filas insertadas.


77 filas insertadas.


103 filas insertadas.


10 filas insertadas.


121 filas insertadas.


82 filas insertadas.


0 filas insertadas.


209 filas insertadas.


2,411 filas insertadas.


79 filas insertadas.


34 filas insertadas.


204 filas insertadas.


643 filas insertadas.


197 filas insertadas.


26 filas insertadas.


430 filas insertadas.


1,966 filas insertadas.


158 filas insertadas.


42 filas insertadas.


5,982 filas insertadas.


0 filas insertadas.


0 filas insertadas.


0 filas insertadas.


34,983 filas insertadas.


0 filas insertadas.


48,795 filas insertadas.


2,057 filas insertadas.


20 filas insertadas.


10 filas insertadas.


6 filas insertadas.


1 fila insertadas.


24 filas insertadas.


0 filas insertadas.


6 filas insertadas.


1 fila insertadas.


313 filas insertadas.


340 filas insertadas.


19,477 filas insertadas.


9,867 filas insertadas.


55 filas insertadas.


0 filas insertadas.


0 filas insertadas.


0 filas insertadas.

Confirmación terminada.

295 filas insertadas.


1,031 filas insertadas.


0 filas insertadas.


0 filas insertadas.


200 filas insertadas.


114 filas insertadas.


507,364 filas insertadas.


309 filas insertadas.


191 filas insertadas.


10 filas insertadas.


0 filas insertadas.


29,679 filas insertadas.


1 fila insertadas.


343,167 filas insertadas.


83 filas insertadas.


363 filas insertadas.


356,193 filas insertadas.


1,172 filas insertadas.


1 fila insertadas.


0 filas insertadas.


41 filas insertadas.


14 filas insertadas.


28,784 filas insertadas.


20 filas insertadas.


28,969 filas insertadas.


2,959,999 filas insertadas.


174 filas insertadas.


0 filas insertadas.


0 filas insertadas.


4,368 filas insertadas.


120,178 filas insertadas.


0 filas insertadas.


0 filas insertadas.


1,136,443 filas insertadas.


0 filas insertadas.


4 filas insertadas.

Confirmación terminada.

6 filas insertadas.


0 filas insertadas.


0 filas insertadas.


15,358 filas insertadas.


95,971 filas insertadas.


1,025,771 filas insertadas.


121,740 filas insertadas.


452,155 filas insertadas.


0 filas insertadas.


0 filas insertadas.


171,307 filas insertadas.


182,658 filas insertadas.


0 filas insertadas.


0 filas insertadas.


660 filas insertadas.


237 filas insertadas.


59,778 filas insertadas.


370 filas insertadas.


0 filas insertadas.


332 filas insertadas.


21 filas insertadas.


13 filas insertadas.


13 filas insertadas.


21 filas insertadas.


1,584 filas insertadas.


267 filas insertadas.


20 filas insertadas.


292 filas insertadas.


267 filas insertadas.


36 filas insertadas.


274 filas insertadas.


15 filas insertadas.

Confirmación terminada.

9 filas insertadas.


3 filas insertadas.


2 filas insertadas.


215 filas insertadas.


292 filas insertadas.


76,648 filas insertadas.


174 filas insertadas.


87,707 filas insertadas.


5,372 filas insertadas.


4,137 filas insertadas.


0 filas insertadas.


0 filas insertadas.


364 filas insertadas.


3 filas insertadas.


3 filas insertadas.


101 filas insertadas.


1,067 filas insertadas.


1,147 filas insertadas.


24,738 filas insertadas.


3 filas insertadas.


1,147 filas insertadas.


200,091 filas insertadas.


3 filas insertadas.


965,607 filas insertadas.


694,467 filas insertadas.


13,012 filas insertadas.


1,341,862 filas insertadas.


1,828,014 filas insertadas.


2,411,536 filas insertadas.


280 filas insertadas.


280 filas insertadas.


225,586 filas insertadas.


137,533 filas insertadas.


78,228 filas insertadas.


481 filas insertadas.


0 filas insertadas.


0 filas insertadas.


3,094 filas insertadas.


0 filas insertadas.

Confirmación terminada.

0 filas insertadas.


2,337 filas insertadas.

Confirmación terminada.
